### PR TITLE
Update ontology.ttl

### PR DESCRIPTION
**Pull request by Ajala111**
Incorporated interface requirements specifications from CCSTMS, covering data models needed for INFRA, ATO, ETCSEngineering, Train Protection (TP), Equipment, Operational Plan (OPP), and that of Balise packet telegram (subset 26).

### CODE REVIEW

**Comment by Ajala111** [comment]
Thanks for the concern and observation raise:

Response to #1: 
The use of multiple namespaces to maintain modularity, as achieved by CCSTMS, has been a topic of extensive discussion during the earlier stages of development. However, the ERA team seems to hold a contrary opinion, insisting that all extensions should adhere to a single base- namespace. From our perspective, as long as functionality is not compromised and the CCSTMS views can still be successfully derived from the model, the intended purpose will be served—albeit with some additional algorithmic effort.

Response to #2: 
Note: this PR is the result of ongoing collaborative efforts between the ERA team and the ERJU "CCSTMS" modeling team. The primary objective is to extend the ERA model to address requirements covered by CCSTMS that are not yet incorporated into the existing model. If you are familiar with CCSTMS, its documentation, and the issues it addresses, then you already have clarity on the problem being tackled by this extension.

Response to #3: 
This has already been addressed on the CCSTMS repo.

Finally, due to some major changes coming from the _/dev_ branch, this specific PR is no longer consistence and will be re-aligned. - still waiting for the final version in 2wks

**Comment by Airy59** [comment]
Thanks for your response. Regarding part of my third point, which corresponds issue number 2 in one of your repositories:

**Copied from repo https://github.com/StructLab/CCS-TMS-1.0:**

###  http://data.europa.eu/949/BufferStopAccuracy
era:BufferStopAccuracy rdf:type owl:Class ;
                       rdfs:subClassOf era:BufferStop ;
                       era:ccsView "ENG" ;
                       dcterms:created "2023-11-13"^^xsd:date ;
                       rdfs:label "BufferStop Accuracy"@en .
                       
**Copied from the other repo, https://github.com/StructLab/ERA-CCSTMS/blob/main/ccstms1_0.ttl:**

###  http://data.europa.eu/949/BufferStopAccuracy
era:BufferStopAccuracy rdf:type owl:Class ;
                       era:ccsView "ENG" ;
                       dcterms:created "2023-11-13"^^xsd:date ;
                       rdfs:label "BufferStop Accuracy"@en .
                       
While the faulty subclassing was apparently corrected in the latter repo, it keeps the issue open, while its sibling repo still has the mistake but no issues altogether.

Besides, you are now publishing two different approved versions (1.0) in two places under the same namespace. What is the intention?

**Comment by Ajala111** [comment]
All ontology related discussions has been moved [here](https://github.com/StructLab/ERA-CCSTMS)

**Comment by Ajala111** [comment]
due to some major changes coming from the /dev branch, this specific PR is no longer consistence

**Pull request closed without merging**
